### ISSUE TITLE
Round-trip mismatch for PFB files with python

### ISSUE THREAD

**Issue by psavery** [hydroframe/parflowio#12]
For some reason, when I round-trip a numpy array to a PFB file and back, I get zeros at the beginning of the array. An example is pasted below. I've tried a few different array shapes and encountered the problem on all of them. Any idea what could be wrong?

We are using this to store data for CLM driver files.

```python
import numpy as np

from parflowio.pyParflowio import PFData


def read_array(file_name):
    data = PFData(file_name)
    data.loadHeader()
    data.loadData()
    return data.viewDataArray()


def write_array(file_name, array):
    data = PFData()
    data.setDataArray(array)
    return data.writeFile(file_name)


array = np.full(25, 34.75).reshape((1, 5, 5))
print(array)

# [[[34.75 34.75 34.75 34.75 34.75]
#   [34.75 34.75 34.75 34.75 34.75]
#   [34.75 34.75 34.75 34.75 34.75]
#   [34.75 34.75 34.75 34.75 34.75]
#   [34.75 34.75 34.75 34.75 34.75]]]

write_array('test.pfb', array)
new_array = read_array('test.pfb')
print(np.around(new_array, 2))

# [[[ 0.    0.   34.75 34.75 34.75]
#   [34.75 34.75 34.75 34.75 34.75]
#   [34.75 34.75 34.75 34.75 34.75]
#   [34.75 34.75 34.75 34.75 34.75]
#   [34.75 34.75 34.75 34.75 34.75]]]
```

System info:
- Ubuntu 20.04
- Python 3.8.5
- numpy-1.19.4
- parflowio-0.0.4

**Comment by psavery** [comment]
More info: I was able to repeat the issue with multiple versions of numpy and python on my system. So I don't think python and numpy versions are related to the issue.

However, the issue did not occur when I tried it on Mac. It has so far only occurred for me on my Linux computer. So it may be OS specific.

**Comment by psavery** [comment]
The problem also occurs for me if I build parflowio locally on my machine. So it doesn't appear to be a problem with the wheels either.

**Comment by arezaii** [comment]
So glad you pointed this out @psavery. This is happening because of some changes we had to make to avoid leaking memory when using the deprecated `getDataArray()` method. This method was removed and replaced by three methods:

- `copyDataArray()`
- `viewDataArray()`
- `moveDataArray()`

`copyDataArray` performs a memory copy of the underlying C array and gives your numpy array ownership of the data.

`viewDataArray` only returns a pointer to the underlying C array, your numpy object does not own that memory and won't free it when it goes out of scope. It will be freed when the PFData object goes out of scope.

`moveDataArray` returns a pointer to the underlying C array **and** transfers ownership of the memory space to the numpy object. The memory will not be freed when the PFData object goes out of scope, but when the numpy object goes out of scope.

So in your example, you would want to use moveDataArray() because your PFData object goes out of scope when your function returns, so you can't rely on the object you created from it anymore.

Here is the corrected code with output:

```
[arezaii@localhost pf_subsetter_testing]$ ipython
Python 3.8.2 (default, Mar 25 2020, 17:03:02)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.18.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import numpy as np
   ...: from parflowio.pyParflowio import PFData
   ...:
   ...:
   ...: def read_array(file_name):
   ...:     data = PFData(file_name)
   ...:     data.loadHeader()
   ...:     data.loadData()
   ...:     return data.moveDataArray()
   ...:
   ...:
   ...: def write_array(file_name, array):
   ...:     data = PFData()
   ...:     data.setDataArray(array)
   ...:     return data.writeFile(file_name)
   ...:
   ...:
   ...: array = np.full(2601 ,34.75).reshape((1, 51, 51))
   ...: print(array)
   ...:
   ...: write_array('test.pfb', array)
   ...: new_array = read_array('test.pfb')
   ...: print(np.around(new_array, 2))
[[[34.75 34.75 34.75 ... 34.75 34.75 34.75]
  [34.75 34.75 34.75 ... 34.75 34.75 34.75]
  [34.75 34.75 34.75 ... 34.75 34.75 34.75]
  ...
  [34.75 34.75 34.75 ... 34.75 34.75 34.75]
  [34.75 34.75 34.75 ... 34.75 34.75 34.75]
  [34.75 34.75 34.75 ... 34.75 34.75 34.75]]]
[[[34.75 34.75 34.75 ... 34.75 34.75 34.75]
  [34.75 34.75 34.75 ... 34.75 34.75 34.75]
  [34.75 34.75 34.75 ... 34.75 34.75 34.75]
  ...
  [34.75 34.75 34.75 ... 34.75 34.75 34.75]
  [34.75 34.75 34.75 ... 34.75 34.75 34.75]
  [34.75 34.75 34.75 ... 34.75 34.75 34.75]]]
```

**Comment by psavery** [comment]
@arezaii This looks great, and thank you for the explanation! Indeed, my problem is solved if I use `moveDataArray()`.

It would be nice if these functions were documented somewhere :wink:
